apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: {{ include "task-tracker-app.fullname" . }}

spec:
  secretName: task-tracker-tls

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - {{ (index .Values.ingress.hosts 0).host }}